# Generated by Django 2.2 on 2020-02-07 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=140),
        ),
        migrations.CreateModel(
            name='Vechicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('VINnumber', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('PurchaseDate', models.DateTimeField(blank=True, default='', null=True)),
                ('LastServiceDate', models.DateTimeField(blank=True, default='', null=True)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
